spring:
  profiles: dev
  h2.console:
    enabled: true
    path: /h2-console
  datasource:
    url: jdbc:h2:mem:funworks
    username: SA
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
security:
  basic:
    enabled: true
    authorize-mode: NONE